// <auto-generated />
namespace IMCMS.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddingToContact : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingToContact));
        
        string IMigrationMetadata.Id
        {
            get { return "201703231938458_AddingToContact"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
